# Generated by Django 3.2.7 on 2021-09-29 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_course', models.IntegerField(choices=[(5, 'Best'), (4, 'Good'), (3, 'Satisfactorily'), (2, 'Bad'), (1, 'Very Bad'), (0, 'Terrible')])),
                ('soft_course', models.IntegerField(choices=[(5, 'Best'), (4, 'Good'), (3, 'Satisfactorily'), (2, 'Bad'), (1, 'Very Bad'), (0, 'Terrible')])),
                ('online_course', models.IntegerField(choices=[(5, 'Best'), (4, 'Good'), (3, 'Satisfactorily'), (2, 'Bad'), (1, 'Very Bad'), (0, 'Terrible')])),
                ('difficulty_of_courses', models.IntegerField(choices=[(5, 'Best'), (4, 'Good'), (3, 'Satisfactorily'), (2, 'Bad'), (1, 'Very Bad'), (0, 'Terrible')])),
                ('hardest_teacher', models.CharField(default=None, max_length=20)),
                ('self_opinion', models.CharField(default=None, max_length=350, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
